language: python

sudo: false

matrix:
  include:

    - os: linux
      python: 3.7
      dist: xenial
    
    - os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=36
      dist: xenial

env:
  global:
  # Doctr deploy key for Quansight/lsst_dashboard
    - secure: "UNia0Igou7jIx/WHfHJOzH19SeLFcIS2bs0Y1c4Qr8PhXo2TDnHfGdJkmkWF5XlndMxOg8RZeHqvMHJA3aHua9z1HspUmcTT8sfVQY7xqLjNm+pi+faOL23LQcqSxzUy0/EQWjRtkUjofjJaS1vI+h6HF8/Gu1DkVzAAQMLkwBePHMwkNTZrUEjKsmzxDWy+V3+GuoEJ1fBPSdnQHGqWftfERn/hVgn6i+Ma/vq+P+y+jbt6QltcSRSUP/ZmveqP52NnrQrQjppH5GcAlGb+TkGJNOuATbhGI8QAaGEQY1d5YtL1zVAvdFycXbzJ+XlibfVJd5HUtPoTdzq++tnwh72Pzs10YcEibUd5VIwuSbnNzlBO5MhecFNOPlCd+4J6ahuskPgKyfU0mvdFRrOedNTzuok7M0QyC9efmvLhH1uKxfDNcahjFCWXLrqnPQtn/Sx56xEh32W0+/L7nhYUZRGjp4F3lOJVNWM7Mklu7UhEs2hbxedgR3By4o3T1BOF7AdLs5yMgRtmcL7yx54bnGUd9WxOPAmarEmbA1rLxKHcl97UtZppB3rBfbFu+vg+xt/kSwPj2AJ9EM/ZaQ166ih9hCmcmagYoabJ7jA0VIOfTSaA4ybSxxftjpTlDXEwk0aqP/H4GA94SIag0W3qBAKfGPfVOp/LMWtbgnT02uI="

before_install:
  # install conda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --add channels conda-forge
  - conda update conda

  # Install dependencies
  - conda env create -f environment.yml
  - conda activate lsst-panel
  - conda install pytest

install:
  - python setup.py install

script:
  - python -m pytest
  - set -e
  - pip install doctr
  - pwd
  - cd docs
  - make html
  - cd ..
  - doctr deploy . --built-docs ./docs/_build/html/ 


      