language: python

sudo: false

matrix:
  include:

    - os: linux
      python: 3.7
      dist: xenial
    
    - os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=36
      dist: xenial

env:
  global:
  # Doctr deploy key for Quansight/lsst_dashboard
  - secure: "AyxY3j8ogAIsf0ZBy8wl7QurzeMmd5NAuPvBNj9vRnkAMCIa0z/yuaJtp+pfmb/ilCIz7lV77eZ+jaJJcCAwlNdDQgFKOA/rStto5PXAP/Ys6+dOz+43urHeKfhlVoPcYo4mTWr+8hKqmk6ywj0KqHzCt3wGuHaT24Yfd8Srjn2OfUMqQ6D0F9p4FGO4vMoHA/pEh7OY8L5Y7YmLkLGkzlFqSFbbuTSSg8LJi6qd9ca1R4yrJDZhrpaAwh7br42bN0gawf2iXcGev+aB0L6+15TlGYSSQLAEO1HAgQzHyGrBxybEqXn7OVtiiMmYVs9Yd37ISHkuxeozTFz4m7cf1uxN4++RaZnZvztbHUC0pv/I8Q6o499EnIpkFikw+4fQLQI0F1iEvgUgxEpjhFLuom+EjEAkjUE0o9w1zt2mwY79aP2vrLVU24BDFaCFn31Sg/5XUnO/ZmT4Jxz6NTbrNH4CNelBIGuNzh2fySqY5SDgcjKSH4L3GY5aEnT/2WFJ7BQd9TW0aA+5Lj3ifEm1D0oRlTIARFQByNNVLca/0UodpmSIPV/nTAa69Oc1JcTlT4vlQznImqUj7XO/3Dp8e81JMpuleg01iO6ginLCJlKS3ERn1JTa0eRuYeoR9xbncmUkWzS1ws9s2YFRWU6sp3wgW5RnP8i1wmAG6xSl/BY="

before_install:
  # install conda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --add channels conda-forge
  - conda update conda

  # Install dependencies
  - conda env create -f environment.yml
  - conda activate lsst-panel
  - conda install pytest

install:
  - python setup.py install

script:
  - python -m pytest
  - set -e
  - pip install doctr
  - cd docs
  - make html
  - cd ..
  - yes | doctr deploy . --built-docs ./docs/_build/html/ --no-require-master

