language: python

sudo: false

python:
  - 3.7

install:
  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update conda

  # Install dependencies
  #- conda install --file requirements/docs.txt
  #- pip install xonda
  #- python setup.py install
  - conda env create -f environment.yml
  - conda activate lsst-panel
  - conda install pytest
  - python setup.py install

script:
  - python -m pytest
