language: python

sudo: false

os:
  - linux
  - osx

python:
  - 3.7

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://repo.continuum.ibrew updateo/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://repo.continuum.ibrew updateo/miniconda/Miniconda3-latest-MacOSX-x86_64.sh ; fi

install:
  # Install conda
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update conda

  # Install dependencies
  - conda env create -f environment.yml
  - conda activate lsst-panel
  - conda install pytest
  - python setup.py install

script:
  - python -m pytest
