name: lsst-panel

channels:
    - conda-forge
    - pyviz
    - defaults

dependencies:
    - python>=3.7
    - param
    - panel
    - holoviews
    - hvplot
    - geoviews
    - numpy
    - pandas
    - dask
    - datashader
    - colorcet
    - jupyterlab
    - fastparquet
    - pytables
    - pyarrow
    - sphinx
    - scikit-learn
    - nbsite
    
