{% set version = "0.0.1" %}

package:
  name: lsst_dashboard
  version: {{ version }}

source:
  url: https://github.com/Quansight/lsst_dashboard/archive/v{{ version }}.tar.gz
  sha1: 58368ff5139f2257423d8f189671fc5149f30af8

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python>=3.7
    - param
    - panel
    - holoviews
    - hvplot
    - geoviews
    - numpy
    - pandas
    - dask
    - datashader
    - colorcet
    - jupyterlab
    - fastparquet
    - pytables
    - pyarrow

test:
  imports:
    - lsst_dashboard

about:
  home: https://github.com/Quansight/lsst_dashboard
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Dashboard for Viewing and Interacting with data from the LSST'

extra:
  recipe-maintainers:
    - kcpevey